### ISSUE TITLE
In Spawn, models without zone equipment will crash

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2015]
If there are no lights, people, electric equipment, etc in a spawn idf file, then the program will crash.

**Comment by kbenne** [comment]
@kuzha and @dhblum I add this issue in response to a model @mwetter sent me that was crashing. There was a bug in models without zone equipment. You might be able to work around by inserting a Light or ElectricEquipment object (even with 0 power) into each zone. The real fix is in the commit above. This is going to require a new spawn binary and we will want to coordinate with @mwetter to update the binaries in MBL.

**Comment by dhblum** [comment]
Thanks a lot Kyle for the fix and suggested workaround.  We could use that until the binaries in MBL are updated.

**Comment by kuzha** [comment]
Thanks @kbenne. I tested the workaround and it works fine now!

**Comment by mwetter** [comment]
This should be fixed now, need testing.

**Comment by kuzha** [comment]
@mwetter 
I did a test with the same model I sent to you before and it still throws the same error. 
My local branch of issue1129_energyplus_zone is synchronized with the remote branch. Did I miss anything?

**Comment by kbenne** [comment]
@kuzha I wonder if you don't have the update. If you locate the "spawn" executable within MBL you can invoke `spawn --version` and I will be able to tell you if you have the proposed fix.

**Comment by kuzha** [comment]
@kbenne 
My version is Spawn-0.0.1-46d0591508. 
About the spawn updating in MBL, it is not clear to me how it should be proceeded. Previously, I just needed to use git lfs and synchronize my local branch to issue1129_energyPlus_zone.
I found this [install.py](https://github.com/lbl-srg/modelica-buildings/blob/issue1129_energyPlus_zone/Buildings/Resources/src/ThermalZones/EnergyPlus/install.py) file and try to install it but it throws this error: _OSError: Failed to find 'lib/libepfmi.so'_, even though this file is already there locally (see screenshot).
<img width="180" alt="Screen Shot 2020-07-16 at 3 51 35 PM" src="https://user-images.githubusercontent.com/18061609/87716037-3d81a480-c77c-11ea-955f-b721abd7744c.png">
Is it worthwhile to add the updating process of spawn in the UserGuide?

**Comment by mwetter** [comment]
@kuzha 
You can verify whether you have the right binaries by running
```
Buildings$ find  Resources/bin/spawn-linux64/ -name '*' | xargs  md5sum
md5sum: Resources/bin/spawn-linux64/: Is a directory
md5sum: Resources/bin/spawn-linux64/lib: Is a directory
754dc43459265ad948c96d20b75f60a4  Resources/bin/spawn-linux64/lib/epfmi.so
b0927ee956008aa705fd6b0c3d560bbe  Resources/bin/spawn-linux64/lib/libepfmi.so
5dbef4fd6a7fdac4759db0914685a0ef  Resources/bin/spawn-linux64/README.md
md5sum: Resources/bin/spawn-linux64/etc: Is a directory
01339e9d5b8bb4453f9fdf1057fe08b7  Resources/bin/spawn-linux64/etc/Energy+.idd
md5sum: Resources/bin/spawn-linux64/bin: Is a directory
7354592a02a232ea5dfff5a3453c6dd5  Resources/bin/spawn-linux64/bin/spawn
```
and comparing the checksums.

Don't run the `install.py` file as this pulls out the last version which may not be the one used for the branch you work on.

**Comment by kuzha** [comment]
@mwetter 
I don't have the following file in my Resources/bin/spawn-linux64/lib folder. All the rest are the same.
754dc43459265ad948c96d20b75f60a4  Resources/bin/spawn-linux64/lib/epfmi.so

How can I get this binary?

**Comment by kbenne** [comment]
@kuzha I can confirm that Spawn-0.0.1-46d0591508 does not have the change that you need which is c6da5cec2fc5324d6e7bdd5516cfed203eb03988. I'll let @mwetter guide you through updating your binaries.

**Comment by mwetter** [comment]
@kuzha It turns out that ` Resources/bin/spawn-linux64/lib/epfmi.so` is not needed on branch `issue1129_energyplus_zone`, and it is not in git. It was left over on my local file system by mistake.

I will integrate the new spawn binary through branch `issue1633_schedulesActuators` but there is still one model (`Validation/Schedule/OneZoneEquipmentScheduleNonSampledOutputVariable.mos`) that fails in the unit tests of Dymola. This needs some further diagnostics before I can merge to `issue1129_energyplus_zone`.

**Comment by mwetter** [comment]
@kuzha : Does your file now work with `issue1633_schedulesActuators` if there are no lights, people, electric equipment, etc? If so, then this issue can be closed.

**Comment by kuzha** [comment]
@mwetter 
Yes the file works now with the branch issue1633_schedulesActuators. We can close this issue.
