### ISSUE TITLE
FMUs that contain Spawn are not self contained

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2054]
This is in referenced to any "parent" FMU that contains a Spawn model, not about the EnergyPlus FMU. If you ask the Modelica compiler to compile a model to FMU, any resources consumed by the model using the Modelica function `Modelica.Utilities.Files.loadResource` will be copied into the resulting FMU's resources directory. For example idf files are loaded using LoadResource https://github.com/lbl-srg/modelica-buildings/blob/19a997dabf44ff709525bc6402060d3eac5baff3/Buildings/ThermalZones/EnergyPlus/Validation/ThermalZone/OneZone.mo#L7. 

The binary requirements of Spawn including epfmi.so and spawn(exe) are not however loaded as resources. Instead the buildingsLibraryRoot is passed to C extensions and the paths into the MBL are determined from there. https://github.com/lbl-srg/modelica-buildings/blob/19a997dabf44ff709525bc6402060d3eac5baff3/Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUZoneClass.mo#L20 The result is that any FMU using Spawn will have attachments to the MBL path that is outside of the context of the FMU.

It would be better to identify epfmi and spawn using loadResource so that 1. The Modelica compiler will copy the resource if you ask for an FMU 2. The correct path for these resources will be identified at simulation time.

**Comment by kbenne** [comment]
@mwetter

**Comment by mwetter** [comment]
Will be added for BOPTEST support.

**Comment by mwetter** [comment]
This is addressed through https://github.com/lbl-srg/modelica-buildings/commit/e410c6f7eed630995fbb9497e194a3a13774d965

The parameter `Boolean generatePortableFMU = false` can be used to exclude/include binaries. By default they are excluded because with OPTIMICA, including them adds on Linux about 5 seconds to the translation time.

**Comment by kbenne** [comment]
Nice. I like the option to turn this off and on. This looks like it will get the resources into the FMU, but I think there is code in the C extension that needs to be updated also. I believe the argument to the C function(s) is path to MBL, not the exe/so paths.

**Comment by mwetter** [comment]
That's correct and need to be fixed. OPTIMICA generates
```
  inflating: modelDescription.xml    
  inflating: binaries/linux64/Buildings_ThermalZones_EnergyPlus_Validation_ThermalZone_OneZone.so  
  inflating: binaries/linux64/libfmilib_shared.so  
  inflating: resources/2/libepfmi-9.0.1.so  
  inflating: resources/0/Zones1.fmu  
  inflating: resources/3/libfmilib_shared.so  
  inflating: resources/1/spawn
```
Let me see why there is a number after the `resources` and how I can know what the number is, other than scanning the file system for `resources/spawn` and `resources/*/spawn`. (Modelon 2020072939000511)

**Comment by mwetter** [comment]
To reproduce: 
1. generate FMU with OPTIMICA and Dymola.
2. run from PyFMI in a way that it does not see the Buildings library.

Kyle has some prototype code with fixes.

**Comment by kbenne** [comment]
Here is what I have so far https://github.com/lbl-srg/modelica-buildings/tree/issue2054_self_contained_spawn. It needs a fair bit of work before considering for merge. At minimum it is hard coded to linux, and that needs to be resolved. I think there are other issues too, but I'll need to dive back into this to remind myself because it has been a while. Gregor's team at CU has reported it working on Dymola.

**Comment by mwetter** [comment]
The development branch is `issue2443_spawn_portable`

**Comment by lambtt** [comment]
> The binaries are included by default and there is no more parameter `generatePortableFMU`. This has been removed in #2759.
> 
> I didn't see a noticeable overhead for including the binaries, so we prefer to keep them in rather than providing many options that may at the end not work across the various Modelica and FMI simulation environments.

Many thanks for that!

**Comment by vincavitabile97** [comment]
Hi all,
I'm Vincenzo Avitabile a student of mechanical engineering for energy and environment from University of Naples Federico II. I'm working about a project that involved Spawn of Energy plus. I have a question for you... Do you know if it's possible to export a readble FMU from Dymola containing Spawn model? When I test FMU with pyFMI I obtain this error "C:/Users/AVITABVi/AppData/Local/Temp/JModelica.org/jm_tmph2v32kf2/resources/Resources/bin/spawn-win64/bin/spawn.exe' does not exist: 'No such file or directory."
Every time I launch pyFMI is generated a folder like jm_tmph2v32kf2 (changing name everytime) but inside effectively there isn’t the spawn.exe.
Do you also have the same problem? How did you solve?
I hope you can help me.
Thanks for your availability

Kind regards,
Vincenzo Avitabile
@mwetter @kbenne

**Comment by vincavitabile97** [comment]
Generating an FMU in Dymola 2021x of "Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.Unconditioned" and testing it with pyFMI I obtain the same error (spawn.exe ' does not exist: 'No such file or directory."), below: 
![image](https://user-images.githubusercontent.com/100144365/155170070-b6df2986-a512-4755-9de5-1cd88dcc7795.png)

So, is it possible to generate an FMU containing a spawn thermal zone?
@mwetter @kbenne

**Comment by mwetter** [comment]
@vincavitabile97: can you try to put the directory that contains your spawn.exe on the system PATH (or add a new system environment variable `SPAWNPATH`) and try with the `master` branch of the Buildings library? This should be fixed in the next release. See also `Buildings.ThermalZones.EnergyPlus.UsersGuide.InvokingEnergyPlus`

**Comment by vincavitabile97** [comment]
Hi @mwetter,
Thanks for the information. I try all the passages suggested before but I still get an error : 
![image](https://user-images.githubusercontent.com/100144365/155290591-8bbd1438-7734-4324-b9b6-d312e91383b8.png)

Kind regards,
Vincenzo

**Comment by mwetter** [comment]
@vincavitabile97 : Are you using the master branch of the Buildings library? Searching on SPAWNPATH is not implemented for the 8.0 or 8.1 release. It is implemented on the master branch and will be part of the next release (9.0.0).

If you use the master, can you set 
`logLevel=Buildings.ThermalZones.EnergyPlus.Types.LogLevels.Verbose` in the `building` instance. Then you should see in the log file where the spawn executable is searched. (The debug message will be improved through https://github.com/lbl-srg/modelica-buildings/pull/2901).

Searching the PATH works on Linux and Windows. I tested it by creating
```
modelica-buildings$ tree test
test
└── spawn-win64
    ├── bin
    │   ├── epfmi.dll
    │   ├── spawn-0.3.0-d6204d26f6.exe
    │   └── VCRUNTIME140.dll
    ├── etc
    │   └── Energy+.idd
    ├── lib
    │   └── epfmi.lib
    └── README.md
```
deleting these files from the local installation, putting `e:\modelica-buildings\test\spawn-win64\bin` on my Windows PATH, restarting Dymola and simulating a model that uses the EnergyPlus coupling.

Executing the version that is packaged with the fmu (in Buildings 8.1) won't work in general as some if not all tool remove the executable flag. This is one reason why for the next release, we search on PATH and SPAWNPATH if it can't be found at the default location.
